### ISSUE TITLE
Add support to configure multiple sudoers groups

### ISSUE THREAD

**Issue by haasad** [appuio/component-openshift4-authentication#62]
## Context

For APPUiO Managed we grant some customer users "admin" rights on the clusters. These rights ideally are identical to the ones granted to the sudoers group via this component. Currently we do this with [adhoc configs](https://github.com/projectsyn/component-adhoc-configurations).

But manually maintaining adhoc configs misses changes like #42 and #61 .

By having an option to add additional sudoers groups, this could be managed via this component.

## Alternatives

Keep doing it with adhoc-configs

**Comment by haasad** [comment]
@simu @glrf I'm happy to try and make a draft for this if you think that's something that's doable and reasonable.

**Comment by simu** [comment]
We're always happy to get contributions.

Regarding implementation, this feature seems pretty straightforward, I'd probably deprecate (read: remove from `class/defaults.yml`, but still use it if present in the hierarchy) the current `sudoGroupName` parameter https://github.com/appuio/component-openshift4-authentication/blob/4a09fd36689cbd89e9adf4e24fed43abdaf3cbbd/class/defaults.yml#L4 and replace it with some setup which allows users to provide multiple group names that should get sudo rights, probably along the lines of:

```yaml
sudoGroups:
  sudoers:
    enabled: true
  customer-admins:
    enabled: false
```

where the keys get interpreted as group names by the component. The component should still accept existing configs using `sudoGroupName`, but print a warning that the parameter is deprecated, see e.g. https://github.com/projectsyn/component-system-upgrade-controller/blob/dee24d712191985ed86a2b1e8edc681f59c58d98/component/main.jsonnet#L12-L22 for an example.

**Comment by haasad** [comment]
Thanks for the feedback, I'll give it a shot when I find the time :+1:

**Comment by simu** [comment]
Alternatively -- I'm not sure what the better approach would be -- you could use the `renderArray()` function in `commodore.libjsonnet`: https://syn.tools/commodore/reference/commodore-libjsonnet.html#_renderarrayarr to implement `sudoGroups` as an array which allows removal of elements by prefixing them with `~`.
